<a href="https://colab.research.google.com/github/Adyypower/Deep-learning-Models-or-topics/blob/main/2_tokenizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
from transformers import BertModel , AutoTokenizer
import pandas as pd
from scipy.spatial.distance import cosine

In [3]:
model_name = 'bert-base-cased'
model = BertModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [4]:
sentence = "When life gives you lemons, don`t make lemonad"
tokens = tokenizer.tokenize(sentence)
print(tokens)

['When', 'life', 'gives', 'you', 'lemon', '##s', ',', 'don', '`', 't', 'make', 'lemon', '##ad']


In [5]:
vocab = tokenizer.vocab
vocab

{'##ッ': 28843,
 '##§': 28161,
 'Tex': 18033,
 'sliding': 7989,
 'AB': 16151,
 'Dex': 23058,
 'Georgie': 22186,
 'Ellie': 10622,
 '##ding': 3408,
 'Singers': 24047,
 'postal': 14889,
 'Bell': 4720,
 '》': 888,
 '##rds': 15093,
 '##„': 28693,
 'Due': 4187,
 'six': 1565,
 'sandstone': 13145,
 'arena': 8176,
 'Ah': 7066,
 '1796': 14342,
 '##К': 28375,
 'Index': 10146,
 '##bra': 6766,
 'Prague': 8254,
 'ease': 7166,
 'リ': 969,
 '##kata': 24011,
 'France': 1699,
 'ּ': 534,
 '##ingly': 15809,
 'oblique': 23455,
 'ュ': 967,
 '##NP': 14576,
 'Smile': 21278,
 'Colours': 23189,
 'Т': 465,
 'distinct': 4966,
 'withdrawal': 10602,
 'left': 1286,
 '`': 169,
 'Bernhard': 23627,
 'flow': 4235,
 'Württemberg': 17565,
 'shocking': 19196,
 'Wisconsin': 4486,
 'scrub': 20712,
 'butcher': 26087,
 'nursery': 17840,
 '##nco': 23573,
 'Hagen': 27080,
 'fl': 1095,
 'Certificate': 14972,
 'epithet': 21397,
 'policing': 27841,
 'Kane': 8119,
 '##ël': 17259,
 'predictions': 23770,
 'Alongside': 26589,
 '1907': 4796,

In [6]:
vocab_df = pd.DataFrame({'token':vocab.keys() , 'id':vocab.values()})
vocab_df.head()

,token,id
0,##ッ,28843
1,##§,28161
2,Tex,18033
3,sliding,7989
4,AB,16151


In [7]:
token_id = tokenizer.encode(sentence)
token_id

[101,
 1332,
 1297,
 3114,
 1128,
 22782,
 1116,
 117,
 1274,
 169,
 189,
 1294,
 22782,
 3556,
 102]

In [8]:
len(tokens)

13

In [9]:
len(token_id)

15

In [10]:
vocab_df.iloc[101]

,101
token,Institutes
id,24496


In [11]:
list(zip(tokens,token_id[1:-1]))

[('When', 1332),
 ('life', 1297),
 ('gives', 3114),
 ('you', 1128),
 ('lemon', 22782),
 ('##s', 1116),
 (',', 117),
 ('don', 1274),
 ('`', 169),
 ('t', 189),
 ('make', 1294),
 ('lemon', 22782),
 ('##ad', 3556)]

In [12]:
tokenizer.decode(token_id)

'[CLS] When life gives you lemons, don ` t make lemonad [SEP]'

In [13]:
tokenizer_out = tokenizer(sentence)
tokenizer_out

{'input_ids': [101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1274, 169, 189, 1294, 22782, 3556, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [14]:
sentence2 = sentence.replace('don`t', '')

In [15]:
tokenizer_2 = tokenizer([sentence,sentence2],padding = True)
tokenizer_2

{'input_ids': [[101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1274, 169, 189, 1294, 22782, 3556, 102], [101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1294, 22782, 3556, 102, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]}

In [16]:
text = 'Tokenize me this please'

In [17]:
encoded_inputs = tokenizer(text, return_tensors='pt')
encoded_inputs

{'input_ids': tensor([[ 101, 1706, 6378, 3708, 1143, 1142, 4268,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [18]:
output = model(**encoded_inputs)

In [19]:
last_hidden_state = output.last_hidden_state
last_hidden_state

tensor([[[ 6.3545e-01,  1.7615e-01,  6.1589e-01,  ..., -1.1664e-01,
           5.5535e-01, -2.4577e-01],
         [ 2.6871e-01,  1.0804e-01, -7.9291e-02,  ...,  8.8401e-02,
           8.2027e-01, -7.8425e-04],
         [ 5.9982e-02,  5.7306e-01, -2.6445e-01,  ...,  2.0249e-01,
          -8.9708e-01,  2.3878e-01],
         ...,
         [-1.6705e-01,  3.0571e-01,  4.3537e-01,  ...,  8.0311e-02,
           2.3093e-01,  1.8002e-01],
         [ 4.5541e-01,  1.2220e-01,  5.8000e-01,  ...,  3.0526e-01,
           5.1684e-01, -2.6089e-01],
         [ 7.1148e-01,  3.9667e-02,  3.6133e-01,  ..., -4.8748e-01,
           5.2401e-01, -8.0548e-01]]], grad_fn=<NativeLayerNormBackward0>)

In [20]:
pooler_output = output.pooler_output
pooler_output

tensor([[-0.7571,  0.5197,  0.9999, -0.9967,  0.9707,  0.9701,  0.9926, -0.9949,
         -0.9859, -0.6731,  0.9896,  0.9993, -0.9988, -0.9999,  0.8604, -0.9850,
          0.9931, -0.5585, -1.0000, -0.5781, -0.6435, -0.9999,  0.1552,  0.9768,
          0.9878,  0.1029,  0.9929,  1.0000,  0.8974, -0.2188,  0.2532, -0.9955,
          0.8232, -0.9994,  0.1654,  0.1601,  0.6032, -0.2848,  0.7803, -0.9705,
         -0.7546, -0.4581,  0.6860, -0.5660,  0.9705,  0.2324,  0.0123,  0.0351,
          0.0350,  0.9999, -0.9770,  0.9985, -0.9960,  0.9980,  0.9982,  0.4647,
          0.9974,  0.1615, -0.9992,  0.3755,  0.9722,  0.2300,  0.9536, -0.2489,
          0.3661, -0.5718, -0.8706,  0.1662, -0.5311,  0.3377,  0.3172,  0.3148,
          0.9917, -0.9334, -0.0862, -0.9375,  0.0015, -0.9999,  0.9716,  1.0000,
          0.7328, -0.9998,  0.9978, -0.2295, -0.7797,  0.6083, -0.9990, -0.9997,
          0.1160, -0.6008,  0.9560, -0.9938,  0.7354, -0.9208,  1.0000, -0.9690,
         -0.1394,  0.4528,  

In [21]:
def predict(text):
  encoded_inputs = tokenizer(text,return_tensors='pt')

  return model(**encoded_inputs)[0]
sentence_1 = 'my name is aditya'
sentence_2 = 'what are you doing'


In [23]:
print(out1.shape)
print(out2.shape)

torch.Size([1, 8, 768])
torch.Size([1, 6, 768])


In [24]:
tokens1 = tokenizer.tokenize(sentence_1)
tokens2 = tokenizer.tokenize(sentence_2)

In [25]:
print(tokens1)
print(tokens2)

['my', 'name', 'is', 'ad', '##ity', '##a']
['what', 'are', 'you', 'doing']


In [29]:
emb = out1[0:, tokens1.index('name'), :].detach()
emb

tensor([[ 6.7967e-03, -4.7840e-02,  1.5943e-01,  1.5315e-01,  2.6451e-02,
          1.0073e-02,  3.7702e-01, -3.7671e-01,  5.8345e-01, -3.8995e-01,
         -2.1744e-02,  7.8322e-01,  3.8983e-02,  3.7204e-01, -1.8876e-01,
          2.4810e-01,  1.0503e-01,  1.5540e-02,  4.1357e-01,  1.1790e-01,
         -2.6546e-01, -1.4298e-01,  1.0904e-01, -1.5613e-01,  8.4355e-02,
         -5.2573e-01,  4.5395e-01,  8.4557e-01,  4.3716e-03,  2.8941e-01,
          1.8594e-01, -1.3061e-02, -3.1456e-01, -1.0287e-01, -6.2651e-01,
         -3.2087e-01,  2.0904e-01,  2.5676e-01,  1.5797e-01, -2.5914e-01,
          9.7465e-02, -1.5056e-01,  6.3346e-01,  2.0006e-01, -3.2625e-01,
          2.8057e-01,  3.1665e-01, -5.1979e-02, -5.6782e-01, -1.8859e-01,
         -2.6256e-01, -2.4563e-01, -2.4067e-01, -3.1601e-01,  2.0720e-02,
         -1.0926e-01,  4.5926e-02, -3.6774e-02,  1.3036e-02,  6.6008e-01,
         -2.2611e-01,  1.6450e-01,  2.5502e-01,  1.2774e-01, -2.0683e-01,
          4.6024e-01, -5.8333e-01,  2.

In [33]:
emb2 = out1[0:, tokens1.index('name'), :].detach()
emb2

tensor([[ 6.7967e-03, -4.7840e-02,  1.5943e-01,  1.5315e-01,  2.6451e-02,
          1.0073e-02,  3.7702e-01, -3.7671e-01,  5.8345e-01, -3.8995e-01,
         -2.1744e-02,  7.8322e-01,  3.8983e-02,  3.7204e-01, -1.8876e-01,
          2.4810e-01,  1.0503e-01,  1.5540e-02,  4.1357e-01,  1.1790e-01,
         -2.6546e-01, -1.4298e-01,  1.0904e-01, -1.5613e-01,  8.4355e-02,
         -5.2573e-01,  4.5395e-01,  8.4557e-01,  4.3716e-03,  2.8941e-01,
          1.8594e-01, -1.3061e-02, -3.1456e-01, -1.0287e-01, -6.2651e-01,
         -3.2087e-01,  2.0904e-01,  2.5676e-01,  1.5797e-01, -2.5914e-01,
          9.7465e-02, -1.5056e-01,  6.3346e-01,  2.0006e-01, -3.2625e-01,
          2.8057e-01,  3.1665e-01, -5.1979e-02, -5.6782e-01, -1.8859e-01,
         -2.6256e-01, -2.4563e-01, -2.4067e-01, -3.1601e-01,  2.0720e-02,
         -1.0926e-01,  4.5926e-02, -3.6774e-02,  1.3036e-02,  6.6008e-01,
         -2.2611e-01,  1.6450e-01,  2.5502e-01,  1.2774e-01, -2.0683e-01,
          4.6024e-01, -5.8333e-01,  2.

In [27]:
out1 = predict(sentence_1)
out2 = predict(sentence_2)

In [30]:
sentence = "When life gives you lemons, don`t make lemonad"
tokens = tokenizer.tokenize(sentence)
token_id = tokenizer.encode(sentence)

print(f"Tokens: {tokens}")
print(f"Token IDs: {token_id}")
print(f"Length of tokens: {len(tokens)}")
print(f"Length of token IDs: {len(token_id)}")
print("\nThe token IDs include special tokens like [CLS] (101) at the beginning and [SEP] (102) at the end.")

Tokens: ['When', 'life', 'gives', 'you', 'lemon', '##s', ',', 'don', '`', 't', 'make', 'lemon', '##ad']
Token IDs: [101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1274, 169, 189, 1294, 22782, 3556, 102]
Length of tokens: 13
Length of token IDs: 15

The token IDs include special tokens like [CLS] (101) at the beginning and [SEP] (102) at the end.


In [31]:
sentence = "When life gives you lemons, don`t make lemonad"
tokens = tokenizer.tokenize(sentence)

# Find the index of the token 'lemons'
index_of_lemons = tokens.index('lemon')

print(f"Tokens: {tokens}")
print(f"Index of 'lemon': {index_of_lemons}")

Tokens: ['When', 'life', 'gives', 'you', 'lemon', '##s', ',', 'don', '`', 't', 'make', 'lemon', '##ad']
Index of 'lemon': 4


In [35]:
cosine(emb.squeeze(0),emb2.squeeze(0))

np.float32(0.0)